import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "./components/CustomCursor";
import localFont from 'next/font/local'

const pixel = localFont({
  src: [
    {
      path: './fonts/PixelOperator8.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '/fonts/PixelOperator8-Bold.ttf',
      weight: '700',
      style: 'bold'
    }
  ]}
)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pixel.className} antialiased`}
      >
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
